# Generated by Django 4.1 on 2022-09-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawatchlist',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
